language: node_js
sudo: required
notifications:
  email: false
node_js:
  - '18'
services:
  - xvfb
addons:
  chrome: stable
after_success:
  - npm run build:lib
  - npm run build:demo
  - cp .git dist/ngx-timeago/ -r # required by semantic release
  - cp README.md dist/ngx-timeago/
  - cd dist/ngx-timeago
  - npm install semantic-release@8.2.3 --no-save
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/demo/
  on:
    branch: master
