name: CI

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Check build
        run: |
          npm run build:lib
          npm run build:demo
